//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cursach1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int IdProduct { get; set; }
        public string InventoryNumber { get; set; }
        public int ProductType { get; set; }
        public string Recipient { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string IsSent { get; set; }
    
        public virtual ProductTypes ProductTypes { get; set; }
    }
}
